apiVersion: apps/v1
kind: Deployment
metadata:
  name: codex-orchestrator
  namespace: codex
  labels:
    app: codex-orchestrator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: codex-orchestrator
  template:
    metadata:
      labels:
        app: codex-orchestrator
    spec:
      containers:
      - name: codex-orchestrator
        image: your-registry/codex-orchestrator:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: PORT
          value: "3000"
        - name: LOG_LEVEL
          value: "info"
        - name: MAX_CONCURRENT_REQUESTS
          value: "10"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: codex-orchestrator
  namespace: codex
spec:
  selector:
    app: codex-orchestrator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
